# Default time-zone properties
default.time-zone.name=Europe/Kiev

# Token properties
token.life-in-hours=10
token.secret=${TOKEN_SECRET}

#Mongo properties
spring.data.mongodb.uri=mongodb://localhost:27017/amazon

spring.main.allow-bean-definition-overriding=true
