version: '3.8'

services:
  storage:
    container_name: mongo
    build:
      context: ..
      dockerfile: /Users/antonshapovalov/git/AgencyAmazon/doker/dev-env/mongo/Dokerfile
    environment:
      - TOKEN_SECRET=my_secret_token
    ports:
      - "27017:27017"