version: '3.8'

services:
  postgres:
    container_name: jarvis-storage
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./main/resources/migrations:/docker-entrypoint-initdb.d


volumes:
  postgres-data:
    driver: local