version: '3.8'

services:
  postgres:
    container_name: bot-jarvis-database
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@SSw0RD321654!
      POSTGRES_DB: jarvis
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: jarvis-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SERVER_PORT=80
      - SERVER_ADDRESS=0.0.0.0
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bot-jarvis-database:5432/jarvis?currentScheme=public
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=P@SSw0RD321654!
      - bot.name=${BOT_NAME}
      - bot.token=${BOT_TOKEN}
    ports:
      - "9080:80"
    restart: on-failure
    volumes:
      - app-images:/app/photos

volumes:
  postgres-data:
  app-images:
