# JPA properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Postgres properties
spring.datasource.url=jdbc:postgresql://localhost:5432/your_database
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.flyway.locations=classpath:db/migrations
